name: flutterDemo
description: Demonstrates building a layout for the "Lakes" app.

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.0
  english_words: ^3.1.0
  http: '>=0.11.3+12'
#  shared_preferences: ^0.1.0

#dev_dependencies:
#  flutter_test:
#    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/lake.jpg